import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'data/models/candidate.dart';
import 'data/models/exam_break.dart';
import 'data/models/exam_session.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Hive
  await Hive.initFlutter();

  // 2. Register Adapters (Generated by hive_generator)
  Hive.registerAdapter(ExamBreakAdapter());
  Hive.registerAdapter(CandidateStatusAdapter());
  Hive.registerAdapter(CandidateAdapter());
  Hive.registerAdapter(SessionStatusAdapter());
  Hive.registerAdapter(ExamSessionAdapter());

  // 3. Open your Hive Box
  await Hive.openBox<ExamSession>('exam_box');

  runApp(
    const ProviderScope(
      child: InvigilatorApp(),
    ),
  );
}

class InvigilatorApp extends StatelessWidget {
  const InvigilatorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Invigilator',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      // We will define these routes next
      initialRoute: '/',
      routes: {
        '/': (context) => const Center(child: Text('Admin Dashboard')),
        '/clock': (context) => const Center(child: Text('TV Clock')),
      },
    );
  }
}
